apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-healing
  namespace: ai-platform

spec:
  replicas: 1

  selector:
    matchLabels:
      app: self-healing

  template:
    metadata:
      labels:
        app: self-healing

    spec:
      serviceAccountName: self-healing-sa

      containers:
        - name: self-healing
          image: bharatdasa/self-healing_ai_ml:v2
          imagePullPolicy: Always

          ports:
            - containerPort: 8000
              name: http

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
